### ISSUE TITLE
Stylesheet Formatting

### ISSUE THREAD

**Issue by cyouh95** [Lileu/dasmotos#2]
For better readability, try putting each property on its own line. For example:

```css
.price {
  font-weight: bold; 
  color: blue;
}
```

https://github.com/Lileu/dasmotos/blob/master/style.css
