### ISSUE TITLE
Shared Properties

### ISSUE THREAD

**Issue by cyouh95** [Lileu/dasmotos#4]
Alternatively, you could specify the following properties for all `h2` elements instead of each individual heading by id.

```css
h2 {
  font-size: 32px; 
  font-weight: bold; 
  color: white;
}
```

https://github.com/Lileu/dasmotos/blob/master/style.css#L3-L5
